<?php 
  if(!defined('PATH_LC'))exit;
$cache_99036f0011d1e55a19b31c9fee6f27f8 = Array
	(
	0=>Array
		(
		'field'=>'mcid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'cate_name',
		'type'=>'varchar(60)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'cate_title',
		'type'=>'varchar(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'is_sys',
		'type'=>'tinyint(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>