<?php 
  if(!defined('PATH_LC'))exit;
$cache_2242f6f2a045ddd0219ef234cff98d74 = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'time',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'name',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'phone',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'id_number',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'job_number',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'company_name',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'salary_month',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'basic_salary',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'should_salary',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'withhold_count',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'really_salary',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'seniority',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'attendance_bonus',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'subsidy_count',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'subsidy_transportation',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'subsidy_house',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	18=>Array
		(
		'field'=>'overtime_count',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	19=>Array
		(
		'field'=>'overtime_cost',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	20=>Array
		(
		'field'=>'prize',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	21=>Array
		(
		'field'=>'qr_prize',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	22=>Array
		(
		'field'=>'end_prize',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	23=>Array
		(
		'field'=>'last_month',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	24=>Array
		(
		'field'=>'file_cost1',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	25=>Array
		(
		'field'=>'file_cost2',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	26=>Array
		(
		'field'=>'absence_deductions',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	27=>Array
		(
		'field'=>'other_deductions',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	28=>Array
		(
		'field'=>'outsource_cost',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	29=>Array
		(
		'field'=>'jinpo',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	30=>Array
		(
		'field'=>'cpf',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	31=>Array
		(
		'field'=>'house_cost',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	32=>Array
		(
		'field'=>'tax',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	33=>Array
		(
		'field'=>'checkoff',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	34=>Array
		(
		'field'=>'open_card',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	35=>Array
		(
		'field'=>'query_number',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	36=>Array
		(
		'field'=>'extra_data',
		'type'=>'text',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>