<?php 
  if(!defined('PATH_LC'))exit;
$cache_42fd65703ddbe5760d9ad47945b1aefa = Array
	(
	0=>Array
		(
		'field'=>'rid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'rname',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'pid',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'state',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'title',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'is_sys',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'sort',
		'type'=>'smallint(5) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>