<?php 
  if(!defined('PATH_LC'))exit;
$cache_fc8b542ee34f3e0eab4a84e0206f1d1f = Array
	(
	0=>Array
		(
		'field'=>'vrid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'regexp',
		'type'=>'varchar(250)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>