<?php 
  if(!defined('PATH_LC'))exit;
$cache_5df5dc02a14ffedc85be8704bb509786 = Array
	(
	0=>Array
		(
		'field'=>'ftid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'name',
		'type'=>'varchar(60)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>