<?php 
  if(!defined('PATH_LC'))exit;
$cache_8fa2eb096d396fb3d883ade1dece4fc7 = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'content',
		'type'=>'varchar(50)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'commission',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'company_name',
		'type'=>'varchar(50)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'job_time',
		'type'=>'varchar(100)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'id_number',
		'type'=>'varchar(100)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'create_time',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'type',
		'type'=>'int(2)',
		'null'=>'NO',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'root',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>