<?php 
  if(!defined('PATH_LC'))exit;
$cache_570cddaf901147e586d03fc5fba5b368 = Array
	(
	0=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'phone',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'username',
		'type'=>'char(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'password',
		'type'=>'char(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'client_id',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'unionid',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'email',
		'type'=>'varchar(45)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'banned',
		'type'=>'tinyint(1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'ban_reason',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'newpass',
		'type'=>'varchar(34)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'newpass_key',
		'type'=>'varchar(32)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'newpass_time',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'created',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'last_ip',
		'type'=>'varchar(40)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'last_login',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'email_verify',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'lng',
		'type'=>'varchar(32)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'lat',
		'type'=>'varchar(32)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	18=>Array
		(
		'field'=>'gender',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	19=>Array
		(
		'field'=>'nickname',
		'type'=>'varchar(100)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	20=>Array
		(
		'field'=>'authid_qq',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	21=>Array
		(
		'field'=>'authid_wx',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	22=>Array
		(
		'field'=>'authid_wb',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	23=>Array
		(
		'field'=>'authtype',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	24=>Array
		(
		'field'=>'avatar',
		'type'=>'varchar(150)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	25=>Array
		(
		'field'=>'commission',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	26=>Array
		(
		'field'=>'hometown',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	27=>Array
		(
		'field'=>'birthday',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	28=>Array
		(
		'field'=>'address',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	29=>Array
		(
		'field'=>'desc',
		'type'=>'varchar(250)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	30=>Array
		(
		'field'=>'from_id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	31=>Array
		(
		'field'=>'is_yewu',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	32=>Array
		(
		'field'=>'is_online',
		'type'=>'int(2) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	33=>Array
		(
		'field'=>'is_bind',
		'type'=>'tinyint(2) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>2,
		'extra'=>''
		),
	34=>Array
		(
		'field'=>'is_newuser',
		'type'=>'tinyint(2) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	35=>Array
		(
		'field'=>'not_read_sids',
		'type'=>'longtext',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	36=>Array
		(
		'field'=>'attention_num',
		'type'=>'int(11) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	37=>Array
		(
		'field'=>'fans_num',
		'type'=>'int(11) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	38=>Array
		(
		'field'=>'sns_num',
		'type'=>'int(11) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	39=>Array
		(
		'field'=>'sign',
		'type'=>'varchar(255)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	40=>Array
		(
		'field'=>'background',
		'type'=>'varchar(255)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	41=>Array
		(
		'field'=>'hometown_id',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	42=>Array
		(
		'field'=>'now_address_id',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	43=>Array
		(
		'field'=>'emotional_state',
		'type'=>'tinyint(1) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	44=>Array
		(
		'field'=>'last_sign',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	45=>Array
		(
		'field'=>'continue_sign_days',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	46=>Array
		(
		'field'=>'type',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	47=>Array
		(
		'field'=>'company_name',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	48=>Array
		(
		'field'=>'resume_phone',
		'type'=>'varchar(15)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	49=>Array
		(
		'field'=>'branchname',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	50=>Array
		(
		'field'=>'salesmanid',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	51=>Array
		(
		'field'=>'salesmanname',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	52=>Array
		(
		'field'=>'salesmanphoneno',
		'type'=>'varchar(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	53=>Array
		(
		'field'=>'normalmanid',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	54=>Array
		(
		'field'=>'qrcode',
		'type'=>'varchar(255)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	55=>Array
		(
		'field'=>'entry_status',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	56=>Array
		(
		'field'=>'entry_time',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>