<?php 
  if(!defined('PATH_LC'))exit;
$cache_daa10249d2a7531000e0ebc3c05fa926 = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'content',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'commission',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'ip',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'username',
		'type'=>'varchar(32)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'company',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'job_time',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'create_time',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'id_number',
		'type'=>'varchar(50)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'type',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'from_id',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'verify',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'root_time',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'root',
		'type'=>'varchar(30)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>