<?php 
  if(!defined('PATH_LC'))exit;
$cache_eda59ab33e3c3fb6c93ec4717e0f4918 = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'keywords',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'class',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'class_two',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'hope_city',
		'type'=>'varchar(200)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'hope_salary',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'hope_career',
		'type'=>'varchar(32)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'star',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'exp',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'origin',
		'type'=>'varchar(255)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'warn',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'create_time',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'update_time',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'is_hot',
		'type'=>'tinyint(3)',
		'null'=>'YES',
		'key'=>'',
		'default'=>3,
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'push_content',
		'type'=>'text',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'is_push',
		'type'=>'tinyint(1) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>