<?php 
  if(!defined('PATH_LC'))exit;
$cache_40318096c4c21be2bc41e624f6e6a079 = Array
	(
	0=>Array
		(
		'field'=>'nid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'name',
		'type'=>'varchar(60)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'title',
		'type'=>'varchar(45)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'state',
		'type'=>'tinyint(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'des',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'sort',
		'type'=>'smallint(4) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'pid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>