<?php 
  if(!defined('PATH_LC'))exit;
$cache_324f90c7bb204a48e4b91264ad68ccef = Array
	(
	0=>Array
		(
		'field'=>'mid',
		'type'=>'int(11) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'mission_name',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'daily_mission',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'mission_type',
		'type'=>'tinyint(3)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'need_num',
		'type'=>'int(11) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'point',
		'type'=>'int(11) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'state',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>1,
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'created_at',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>