<?php 
  if(!defined('PATH_LC'))exit;
$cache_5ff88a7d80f67434aae4db4ed1ad6e5e = Array
	(
	0=>Array
		(
		'field'=>'gid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'title',
		'type'=>'varchar(200)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'desc',
		'type'=>'varchar(500)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'amount',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'price',
		'type'=>'decimal(10,2) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'img',
		'type'=>'varchar(250)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'start_time',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'end_time',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'created',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'status',
		'type'=>'int(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'type',
		'type'=>'tinyint(1) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>