<?php 
  if(!defined('PATH_LC'))exit;
$cache_d925358be0b6370d3612bd2c911f672d = Array
	(
	0=>Array
		(
		'field'=>'uiid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'name',
		'type'=>'varchar(250)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'birthday',
		'type'=>'varchar(32)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'job_year',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'origin_provice',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'origin_city',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'origin_town',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'tel',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'gender',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'marital_status',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'work_exp',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'cert_type',
		'type'=>'tinyint(3) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'id_number',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'profile',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	15=>Array
		(
		'field'=>'link_provice',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	16=>Array
		(
		'field'=>'link_city',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	17=>Array
		(
		'field'=>'link_town',
		'type'=>'int(10) unsigned',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	18=>Array
		(
		'field'=>'link_email',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	19=>Array
		(
		'field'=>'avatar',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	20=>Array
		(
		'field'=>'hometown',
		'type'=>'varchar(30)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	21=>Array
		(
		'field'=>'photo',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	22=>Array
		(
		'field'=>'verify',
		'type'=>'int(10)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	23=>Array
		(
		'field'=>'card_address',
		'type'=>'varchar(200)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	24=>Array
		(
		'field'=>'card_start_time',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	25=>Array
		(
		'field'=>'card_end_time',
		'type'=>'varchar(100)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	26=>Array
		(
		'field'=>'face_base',
		'type'=>'varchar(250)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	27=>Array
		(
		'field'=>'back_base',
		'type'=>'varchar(250)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	28=>Array
		(
		'field'=>'create_time',
		'type'=>'int(10)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	29=>Array
		(
		'field'=>'apply_time',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>