<?php 
  if(!defined('PATH_LC'))exit;
$cache_f019cee157a709210c790d7311a144f9 = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(11) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'type',
		'type'=>'tinyint(1)',
		'null'=>'YES',
		'key'=>'',
		'default'=>5,
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'code',
		'type'=>'varchar(20)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'mobile',
		'type'=>'varchar(30)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'created',
		'type'=>'int(11)',
		'null'=>'YES',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>