<?php 
  if(!defined('PATH_LC'))exit;
$cache_4cf1e6d44f53ca92d222d378e02547e7 = Array
	(
	0=>Array
		(
		'field'=>'fid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'mid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'buid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'create_at',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		)
	);
?>