<?php 
  if(!defined('PATH_LC'))exit;
$cache_f5c67f56c467c45542b7623d976deb8e = Array
	(
	0=>Array
		(
		'field'=>'recruit_comment_id',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'uvatar',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'unickname',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'bcid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'buid',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'bunickname',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'buvatar',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'company_id',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'company_name',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'recruit_id',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'recruit_name',
		'type'=>'varchar(255)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'content',
		'type'=>'text',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'state',
		'type'=>'int(5)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	14=>Array
		(
		'field'=>'create_at',
		'type'=>'int(11)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>