<?php 
  if(!defined('PATH_LC'))exit;
$cache_4cf2fbc994a505079ff04fbd6b15bcdf = Array
	(
	0=>Array
		(
		'field'=>'id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>1,
		'default'=>'',
		'extra'=>'auto_increment'
		),
	1=>Array
		(
		'field'=>'uid',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	2=>Array
		(
		'field'=>'recruit_id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	3=>Array
		(
		'field'=>'created',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	4=>Array
		(
		'field'=>'company_name',
		'type'=>'varchar(25)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	5=>Array
		(
		'field'=>'recruit_name',
		'type'=>'varchar(20)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	6=>Array
		(
		'field'=>'company_id',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	7=>Array
		(
		'field'=>'type',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'0',
		'extra'=>''
		),
	8=>Array
		(
		'field'=>'star',
		'type'=>'float(5,1)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	9=>Array
		(
		'field'=>'address',
		'type'=>'varchar(50)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	10=>Array
		(
		'field'=>'recruit_num',
		'type'=>'varchar(4)',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	11=>Array
		(
		'field'=>'work_exp',
		'type'=>'tinyint(3) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	12=>Array
		(
		'field'=>'salary',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		),
	13=>Array
		(
		'field'=>'degree',
		'type'=>'int(10) unsigned',
		'null'=>'NO',
		'key'=>'',
		'default'=>'',
		'extra'=>''
		)
	);
?>